package hbi.core.test.dto;

/**Auto Generated By Hap Code Generator**/
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import com.hand.hap.mybatis.annotation.ExtensionAttribute;
import org.hibernate.validator.constraints.Length;
import javax.persistence.Table;
import com.hand.hap.system.dto.BaseDTO;
import org.hibernate.validator.constraints.NotEmpty;
@ExtensionAttribute(disable=true)
@Table(name = "z_test")
public class Test extends BaseDTO {

     public static final String FIELD_ID = "id";
     public static final String FIELD_NAME = "name";
     public static final String FIELD_AGE = "age";


     @Id
     @GeneratedValue(generator = GENERATOR_TYPE)
     private Long id;

     @NotEmpty
     @Length(max = 255)
     private String name;

     private Long age;


     public void setId(Long id){
         this.id = id;
     }

     public Long getId(){
         return id;
     }

     public void setName(String name){
         this.name = name;
     }

     public String getName(){
         return name;
     }

     public void setAge(Long age){
         this.age = age;
     }

     public Long getAge(){
         return age;
     }

     }
